import asyncio
from pathlib import Path

from backend.core.config import app_config
from backend.core.steps.step_export import find_export_splat

_README_SPLATFORGE = """\
# SplatForge Scene — README
==============================

This export was generated by the SfM Splat Pipeline App using the SplatForge
Blender add-on.

## Contents
  scene.blend  — Blender scene with the 3D Gaussian Splatting object imported
                 via SplatForge.
  splat.ply    — the trained splat this scene points at (spirula train, step 4).
  mesh.*       — the surface mesh, if step 5 was asked for one.

## How to use
1. Install Blender 4.x or newer (https://www.blender.org/download/)
2. Install the SplatForge add-on from the Blender add-on market or from source.
3. Open scene.blend in Blender.
4. The Gaussian splat object is ready to render or export.

## Re-importing manually
If you want to re-import the PLY directly:
  Edit > Preferences > Add-ons > Install → select SplatForge
  File > Import > 3D Gaussian Splat (.ply)

## Notes
  - scene.blend is linked to splat.ply in THIS directory — keep them together.
  - splat.ply is a hard link to train/run/step-*.ckpt/splat.ply inside the
    project. Copy the folder rather than moving one file out of it.
"""


async def run_blender(project_path: Path, broadcast_fn, settings: dict) -> dict:
    """Calls Blender headless with the splatforge import script."""
    blender_exe = app_config.tools.blender_exe_path
    if not blender_exe:
        raise FileNotFoundError(
            "blender_exe_path is not configured.\n"
            "Set blender_exe_path in Settings."
        )

    export_dir = project_path / "export"
    # Not `glob("*.ply")[0]`: with `mesh --format ply` the export holds
    # `mesh.ply` too, and it sorts first — Blender would import a surface mesh
    # as a gaussian cloud. `find_export_splat` knows which file step 5 wrote as
    # the splat.
    ply = find_export_splat(export_dir)
    if ply is None:
        raise FileNotFoundError(
            f"No splat .ply in {export_dir}. Run step 5 first — it is what puts "
            "the trained splat there."
        )

    out_blend = export_dir / "scene.blend"
    script = Path(__file__).parents[2] / "scripts" / "blender_splatforge.py"

    cmd = [
        blender_exe,
        "--background",
        "--python", str(script),
        "--", "--ply", str(ply), "--out", str(out_blend),
    ]
    await broadcast_fn("blender", "INFO", f"[Blender] Running: {' '.join(cmd)}")

    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.STDOUT,
    )

    try:
        async for raw in proc.stdout:
            line = raw.decode("utf-8", errors="replace").strip()
            await broadcast_fn("blender", "INFO", line)

        await asyncio.wait_for(proc.wait(), timeout=1800)
    except asyncio.TimeoutError:
        proc.kill()
        raise RuntimeError("Blender timed out after 30 minutes")
    except asyncio.CancelledError:
        # An aborted step must not leave Blender running headless.
        if proc.returncode is None:
            proc.kill()
        raise

    if proc.returncode != 0:
        raise RuntimeError(f"Blender exited with code {proc.returncode}")

    # No `.format()` any more: the only placeholder was `supersplat_url`, which
    # left `config.json` with the two CUDA tools (§12, 2026-08-27). Reading it
    # here raised AttributeError on every step 6, after Blender had already run.
    (export_dir / "README_SPLATFORGE.txt").write_text(
        _README_SPLATFORGE, encoding="utf-8"
    )

    await broadcast_fn(
        "blender", "SUCCESS",
        f"[Blender] Scene exported → {out_blend}",
        progress=1.0,
    )
    return {"blend_path": str(out_blend)}
